### ISSUE TITLE
Support non-ascii characters in iex

### ISSUE THREAD

**Issue by tallakt** [ElixirWin/ChocolateyPackages#23]
When using iex installed from chocolatey (v 1.0.4), any international characters, for example given as a string, are not handled properly by iex.

eg:

    C:\Users\tveidet>iex.bat
    Interactive Elixir (1.0.4) - press Ctrl+C to exit (type h() ENTER for help)
    iex(1)> "æøå"
    ** (UnicodeConversionError) invalid encoding starting at <<145, 155, 134, 34, 10>>
        (elixir) lib/string.ex:1351: String.to_char_list/1

I think this is related to Windows' missing support for utf-8 by default in the cmd shell (pure speculation of course, but soming from someone depending on iconv almost daily). 

You can get around this by running the windowed version of iex: `iex.bat --werl`

The problem I think relates to elixir itself and not the chocolatey portion, but I might be wrong

**Comment by OnorioCatenacci** [comment]
I am going to close this issue because I think it is in Elixir itself and not related to chocolatey.
