### ISSUE TITLE
Shim files not available at chocolatey bin directory

### ISSUE THREAD

**Issue by usoliveira** [ElixirWin/ChocolateyPackages#28]
After installing Elixir 1.2.3, the ".bat" files became available at Lib bin directory, but are not copied or linked at main chocolatey bin directory, so its not available from windows Path once you don't put the full elixir path manually to env variables.

For that reason, when uninstalling Elixir Chocolatey package, it returns errors because the ".bat" files they look aren't at chocolatey bin dir.

**Comment by OnorioCatenacci** [comment]
Hi,

I need to do a bit of work on the CNG package for Elixir when I get a bit more time.  I will check this when I do my other work.  Thanks for letting me know!

--
Onorio

**Comment by OnorioCatenacci** [comment]
The uninstall script attempts to remove the bat files for backwards compatibility.  At one point the package did put .bat files in that directory and so if someone calls update from an older version of the package those files may need to be removed. I realize it's an error if you don't have an older version of the CNG package installed but I'd rather display the incorrect error message than not clean up after the package.

**Comment by usoliveira** [comment]
Hi. I agree with you about mantain backward compatibility, but the problem
I think is that installation script is not coping the bat files to that
folder anymore, and because that, it is not available from path anymore. I
think correcting the copy to main choco bin dir will do the job!

Em Sex, 18 de mar de 2016 16:04, Onorio Catenacci <notifications@github.com>
escreveu:

> The uninstall script attempts to remove the bat files for backwards
> compatibility. At one point the package did put .bat files in that
> directory and so if someone calls update from an older version of the
> package those files may need to be removed. I realize it's an error if you
> don't have an older version of the CNG package installed but I'd rather
> display the incorrect error message than not clean up after the package.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ElixirWin/ChocolateyPackages/issues/28#issuecomment-198497457>
>
-- 
--
Ulisses Oliveira

**Comment by usoliveira** [comment]
I checked that is is really adding lib/bin directory to Path. So, no problem for me. Maybe I get some problem because system user privileges! But its ok!! Thanks for help!

**Comment by OnorioCatenacci** [comment]
I did want to tell you that I had that same thought about simply copying
the batch files to /ProgramData/Chocolatey/bin.  In fact I tried that a
couple of revisions ago.  I am not sure why but it just won't work.  I
think the issue is that the batch files don't find the beam files correctly
but I didn't dig far into it.

I mean to say you've got the right idea.  It just doesn't work for some
reason.

**Comment by usoliveira** [comment]
Hi friend. Do you think its possible to add a validation like the one below, in the Uninstall script for each path, so it doesn't throw any errors?

`If (Test-Path "$env:ChocolateyInstall/bin/iex.bat") { Remove-Item "$env:ChocolateyInstall/bin/iex.bat" }`

**Comment by OnorioCatenacci** [comment]
That's a good suggestion. I'll make the change for the next version of the Elixir CNG package.

**Comment by usoliveira** [comment]
Also, I would suggest to add the path at "Machine" scope. Chocolatey asks for administrative grant to run, and so, the Path variable changed, will be the admin path, not the user.

`Install-ChocolateyEnvironmentVariable "Path" "$($env:Path);$elixirPath" Machine`

**Comment by OnorioCatenacci** [comment]
Good suggestion.

On Wed, Mar 23, 2016 at 8:43 AM, Ulisses Oliveira <notifications@github.com>
wrote:

> Also, I would suggest to add the path at "Machine" scope. Chocolatey asks
> for administrative grant to run, and so, the Path variable changed, will be
> the admin path, not the user.
>
> Install-ChocolateyEnvironmentVariable "Path" "$($env:Path);$elixirPath"
> Machine
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/ElixirWin/ChocolateyPackages/issues/28#issuecomment-200331122>
>



-- 
Onorio Catenacci

http://onor.io
http://www.google.com/+OnorioCatenacci
