### ISSUE TITLE
Elixir package is butchering system path

### ISSUE THREAD

**Issue by wduncanfraser** [ElixirWin/ChocolateyPackages#33]
The current way the Elixir package updates the system path is butchering it. 

```powershell
Install-ChocolateyEnvironmentVariable "Path" "$($env:Path);$elixirPath" Machine
```
The above is line 21 fro Elixir/tools/chocolateyInstall.ps1

This essentially takes everything that the user may be setting via their powershell profiles, any temporary changes to $env:Path they have made in their powershell session, translates variables in the system path such as %SystemRoot% and shoves them all into the permanent system path.

For example, my system path prior to install:
`C:\Python27\;C:\Python27\Scripts;C:\Program Files\VanDyke Software\Clients\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Git\cmd;C:\HashiCorp\Vagrant\bin;C:\opscode\chefdk\bin\;C:\Program Files\Rust stable GNU 1.10\bin;C:\ProgramData\chocolatey\bin
`

After:
`C:\Python27\;C:\Python27\Scripts;C:\Program Files\VanDyke Software\Clients\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Git\cmd;C:\HashiCorp\Vagrant\bin;C:\opscode\chefdk\bin\;C:\Program Files\Rust stable GNU 1.10\bin;C:\ProgramData\chocolatey\bin;C:\Users\duncan\AppData\Local\atom\bin;C:\Program Files\Docker Toolbox;C:\tools\mingw64\bin;C:/opscode/chefdk/bin;C:/Users/duncan/AppData/Local/chefdk/gem/ruby/2.1.0/bin;C:/opscode/chefdk/embedded/bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\ConEmu\ConEmu\Scripts;C:\Program Files\ConEmu;C:\Program Files\ConEmu\ConEmu;C:\Users\duncan\.cargo\bin;C:\HashiCorp\terraform;C:\HashiCorp\packer;C:\Program Files\VMware\VMware OVF Tool;C:/opscode/chefdk/embedded/git/usr/bin;;C:\ProgramData\chocolatey\lib\Elixir/bin`

**Comment by michaelkschmidt** [comment]
@wduncanfraser can you test my fix and verify it works for you as well?  I was able to reproduce on my machine, but having a second verification would be nice :smile:
