### ISSUE TITLE
Shims broken for Erlang 21.0.1

### ISSUE THREAD

**Issue by catlion** [ElixirWin/ChocolateyPackages#44]
```
Downloading erlang 64 bit
  from 'https://www.erlang.org/download/otp_win64_21.0.1.exe'
Progress: 100% - Completed download of C:\Users\Admin\AppData\Local\Temp\chocolatey\erlang\21.0.1\otp_win64_21.0.1.exe (87.46 MB).
Download of otp_win64_21.0.1.exe (87.46 MB) completed.
Hashes match.
Installing erlang...
erlang has been installed.
Added C:\ProgramData\chocolatey\bin\erl.exe shim pointed to 'c:\program files/erl10.0/erts-10.0/bin/erl.exe'.
Added C:\ProgramData\chocolatey\bin\werl.exe shim pointed to 'c:\program files/erl10.0/erts-10.0/bin/werl.exe'.
Added C:\ProgramData\chocolatey\bin\erlc.exe shim pointed to 'c:\program files/erl10.0/erts-10.0/bin/erlc.exe'.
Added C:\ProgramData\chocolatey\bin\escript.exe shim pointed to 'c:\program files/erl10.0/erts-10.0/bin/escript.exe'.
Added C:\ProgramData\chocolatey\bin\dialyzer.exe shim pointed to 'c:\program files/erl10.0/erts-10.0/bin/dialyzer.exe'.
```

Please note `erl10.0` in path, should be `erl10.0.1`

**Comment by OnorioCatenacci** [comment]
On Sat, 2018-06-30 at 02:20 -0700, Artem wrote:
> Downloading erlang 64 bit  from 'https://www.erlang.org/download/otp_
> win64_21.0.1.exe'Progress: 100% - Completed download of
> C:\Users\Admin\AppData\Local\Temp\chocolatey\erlang\21.0.1\otp_win64_
> 21.0.1.exe (87.46 MB).Download of otp_win64_21.0.1.exe (87.46 MB)
> completed.Hashes match.Installing erlang...erlang has been
> installed.Added C:\ProgramData\chocolatey\bin\erl.exe shim pointed to
> 'c:\program files/erl10.0/erts-10.0/bin/erl.exe'.Added
> C:\ProgramData\chocolatey\bin\werl.exe shim pointed to 'c:\program
> files/erl10.0/erts-10.0/bin/werl.exe'.Added
> C:\ProgramData\chocolatey\bin\erlc.exe shim pointed to 'c:\program
> files/erl10.0/erts-10.0/bin/erlc.exe'.Added
> C:\ProgramData\chocolatey\bin\escript.exe shim pointed to 'c:\program
> files/erl10.0/erts-10.0/bin/escript.exe'.Added
> C:\ProgramData\chocolatey\bin\dialyzer.exe shim pointed to
> 'c:\program files/erl10.0/erts-10.0/bin/dialyzer.exe'.
> Please note erl10.0 in path instead of erl10.0.1
> 
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

I've made a change that should fix this.  Please try to download
21.0.1.20180701 when you can and double check that this is
fixed.  Thanks for the bug report!
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
> 5493e4bb","name":"GitHub"},"entity":{"external_key":"github/ElixirWin
> /ChocolateyPackages","title":"ElixirWin/ChocolateyPackages","subtitle
> ":"GitHub repository","main_image_url":"https://assets-cdn.github.com
> /images/email/message_cards/header.png","avatar_image_url":"https://a
> ssets-
> cdn.github.com/images/email/message_cards/avatar.png","action":{"name
> ":"Open in GitHub","url":"https://github.com/ElixirWin/ChocolateyPack
> ages"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Shims
>  broken for Erlang 21.0.1 (#44)"}],"action":{"name":"View
> Issue","url":"https://github.com/ElixirWin/ChocolateyPackages/issues/
> 44"}}}
> [
> {
> "@context": "http://schema.org",
> "@type": "EmailMessage",
> "potentialAction": {
> "@type": "ViewAction",
> "target": "https://github.com/ElixirWin/ChocolateyPackages/issues/44"
> ,
> "url": "https://github.com/ElixirWin/ChocolateyPackages/issues/44",
> "name": "View Issue"
> },
> "description": "View this Issue on GitHub",
> "publisher": {
> "@type": "Organization",
> "name": "GitHub",
> "url": "https://github.com"
> }
> },
> {
> "@type": "MessageCard",
> "@context": "http://schema.org/extensions",
> "hideOriginalBody": "false",
> "originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
> "title": "Shims broken for Erlang 21.0.1 (#44)",
> "sections": [
> {
> "text": "",
> "activityTitle": "**Artem**",
> "activityImage": "https://assets-cdn.github.com/images/email/message_
> cards/avatar.png",
> "activitySubtitle": "@catlion",
> "facts": [
> {
> "name": "Repository: ",
> "value": "ElixirWin/ChocolateyPackages"
> },
> {
> "name": "Issue #: ",
> "value": 44
> }
> ]
> }
> ],
> "potentialAction": [
> {
> "name": "Add a comment",
> "@type": "ActionCard",
> "inputs": [
> {
> "isMultiLine": true,
> "@type": "TextInput",
> "id": "IssueComment",
> "isRequired": false
> }
> ],
> "actions": [
> {
> "name": "Comment",
> "@type": "HttpPOST",
> "target": "https://api.github.com",
> "body": "{\n\"commandName\":
> \"IssueComment\",\n\"repositoryFullName\":
> \"ElixirWin/ChocolateyPackages\",\n\"issueId\":
> 44,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
> }
> ]
> },
> {
> "name": "Close issue",
> "@type": "HttpPOST",
> "target": "https://api.github.com",
> "body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\":
> \"ElixirWin/ChocolateyPackages\",\n\"issueId\": 44\n}"
> },
> {
> "targets": [
> {
> "os": "default",
> "uri": "https://github.com/ElixirWin/ChocolateyPackages/issues/44"
> }
> ],
> "@type": "OpenUri",
> "name": "View on GitHub"
> },
> {
> "name": "Unsubscribe",
> "@type": "HttpPOST",
> "target": "https://api.github.com",
> "body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\":
> 351773228\n}"
> }
> ],
> "themeColor": "26292E"
> }
> ]

**Comment by catlion** [comment]
Perfect, thank you!

**Comment by OnorioCatenacci** [comment]
Thanks for making me aware of the problem!
